# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_design.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(267, 419)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 9, 241, 351))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.login_label.setObjectName("login_label")
        self.verticalLayout.addWidget(self.login_label)
        self.username_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.username_label.setObjectName("username_label")
        self.verticalLayout.addWidget(self.username_label)
        self.username_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.verticalLayout.addWidget(self.username_lineEdit)
        self.password_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.password_label.setObjectName("password_label")
        self.verticalLayout.addWidget(self.password_label)
        self.password_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout.addWidget(self.password_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.login_feedback_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.login_feedback_label.setText("")
        self.login_feedback_label.setObjectName("login_feedback_label")
        self.verticalLayout.addWidget(self.login_feedback_label, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.signInButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.signInButton.setObjectName("signInButton")
        self.verticalLayout.addWidget(self.signInButton, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 221, 341))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.register_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.register_label.setObjectName("register_label")
        self.verticalLayout_2.addWidget(self.register_label)
        self.register_name_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.register_name_label.setObjectName("register_name_label")
        self.verticalLayout_2.addWidget(self.register_name_label)
        self.register_name_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.register_name_lineEdit.setObjectName("register_name_lineEdit")
        self.verticalLayout_2.addWidget(self.register_name_lineEdit)
        self.register_username_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.register_username_label.setObjectName("register_username_label")
        self.verticalLayout_2.addWidget(self.register_username_label)
        self.register_username_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.register_username_lineEdit.setObjectName("register_username_lineEdit")
        self.verticalLayout_2.addWidget(self.register_username_lineEdit)
        self.register_password_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.register_password_label.setObjectName("register_password_label")
        self.verticalLayout_2.addWidget(self.register_password_label)
        self.register_password_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.register_password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.register_password_lineEdit.setObjectName("register_password_lineEdit")
        self.verticalLayout_2.addWidget(self.register_password_lineEdit)
        self.register_confirmPassword_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.register_confirmPassword_label.setObjectName("register_confirmPassword_label")
        self.verticalLayout_2.addWidget(self.register_confirmPassword_label)
        self.register_confirmPassword_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.register_confirmPassword_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.register_confirmPassword_lineEdit.setObjectName("register_confirmPassword_lineEdit")
        self.verticalLayout_2.addWidget(self.register_confirmPassword_lineEdit)
        self.register_message = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.register_message.setObjectName("register_message")
        self.verticalLayout_2.addWidget(self.register_message)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.registerButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout_2.addWidget(self.registerButton, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 267, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew_User = QtWidgets.QMenu(self.menubar)
        self.menuNew_User.setObjectName("menuNew_User")
        self.menuLogin = QtWidgets.QMenu(self.menubar)
        self.menuLogin.setObjectName("menuLogin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.actionLogin_Page = QtWidgets.QAction(MainWindow)
        self.actionLogin_Page.setObjectName("actionLogin_Page")
        self.menuFile.addAction(self.actionExit)
        self.menuNew_User.addAction(self.actionRegister)
        self.menuLogin.addAction(self.actionLogin_Page)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuNew_User.menuAction())
        self.menubar.addAction(self.menuLogin.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign On"))
        self.login_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Sign In</span></p></body></html>"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.signInButton.setText(_translate("MainWindow", "Login"))
        self.register_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Register</span></p></body></html>"))
        self.register_name_label.setText(_translate("MainWindow", "Name"))
        self.register_username_label.setText(_translate("MainWindow", "Username"))
        self.register_password_label.setText(_translate("MainWindow", "<html><head/><body><p>Password <span style=\" font-size:9pt;\">(6 or more characters)</span></p></body></html>"))
        self.register_confirmPassword_label.setText(_translate("MainWindow", "Confirm Password"))
        self.register_message.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\"><br/></span></p></body></html>"))
        self.registerButton.setText(_translate("MainWindow", "Register"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuNew_User.setTitle(_translate("MainWindow", "New User?"))
        self.menuLogin.setTitle(_translate("MainWindow", "Login"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRegister.setText(_translate("MainWindow", "Register"))
        self.actionLogin_Page.setText(_translate("MainWindow", "Login Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

